[package]
name = "nebula-components"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
nebula-core = { path = "../nebula-core" }
tracing = { workspace = true }
taffy = "0.5"
