[package]
name = "nebula-renderer-cpu"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
softbuffer = { workspace = true }
tiny-skia = { workspace = true }
raw-window-handle = { workspace = true }
tracing = { workspace = true }
