[package]
name = "nebula-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tracing = { workspace = true }
fontdue = "0.9"
taffy = "0.5"
